version: '3.8'

services:
  oracle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle12c
    ports:
      - "1521:1521"
    volumes:
      - ./data:/opt/oracle/data
      - ./scripts:/opt/oracle/scripts

   sqlplus:
    image: oracleinanutshell/oracle-xe-11g
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]
