# Use the official Oracle Linux base image
FROM oraclelinux:7-slim

# Install required packages
RUN yum -y install oracle-database-ee-12c \
    && yum clean all \
    && rm -rf /var/cache/yum

# Copiar arquivos para o contêiner

COPY ./scripts /opt/oracle/scripts
COPY ./data /opt/oracle/data

# Expose the port for Oracle Database
EXPOSE 1521

# Tornar o script executável
RUN chmod +x /opt/oracle/scripts/*.sh

# Definir o ponto de entrada
#ENTRYPOINT ["/opt/oracle/scripts/init.sh"]

# Comando para iniciar o Oracle e executar os scripts de inicialização
CMD ["/bin/bash", "-c", "/opt/oracle/scripts/init.sh && /bin/bash"]
