version: '3.8'

services:
  oracle:
    build:
      dockerfile: Dockerfile
    container_name: oracle11g
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
        ORACLE_PWD: oracle
    volumes:
      - ../data:/opt/oracle/oradata
      - ../scripts:/opt/oracle/scripts
    command: ["/opt/oracle/scripts/init.sh"]

