version: '3.8'

services:
  oracle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle11g
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_PWD=your_password
    volumes:
      - oracle-data:/u01/app/oracle
    command: ["/opt/oracle/scripts/init.sh"]
